server:
  tomcat:
    max-swallow-size: 100MB
  servlet:
    context-path: /mt/v1
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:testdb # Connect to an in-memory H2 database named 'testdb'
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true # Enable the H2 console for web-based access
      path: /h2-console # Path to access the H2 console